# Generated by Django 5.1.2 on 2024-12-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_accounttable'),
    ]

    operations = [
        migrations.CreateModel(
            name='familytable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100, verbose_name="Father's Name")),
                ('mother_name', models.CharField(max_length=100, verbose_name="Mother's Name")),
                ('marital_status', models.CharField(max_length=50, verbose_name='Marital Status')),
                ('spouse_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Spouse Name')),
                ('number_of_children', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Children')),
            ],
        ),
    ]
